# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.after(:all) do
    FileUtils.rm_rf('labels')
  end

end

require_relative '../lib/dhl'
# For Ruby < 1.9.3, use this instead of require_relative
# require(File.expand_path('../../lib/dish', __FILE__))

require 'time'
require 'factory_girl'
FactoryGirl.find_definitions
require 'pry'

require 'rspec/autorun'
require 'webmock/rspec'
require 'vcr'

#VCR config
VCR.configure do |config|
  config.cassette_library_dir = 'spec/fixtures/dhl_cassettes'
  config.hook_into :webmock
  config.allow_http_connections_when_no_cassette = true
end
